export const ON_DETECTED = 'ON_DETECTED'
export const ON_SEARCH = 'ON_SEARCH'
export const LOG_IN_STANDARD = 'LOG_IN_STANDARD'
export const LOG_OUT_STANDARD = 'LOG_OUT_STANDARD'
export const LOG_IN_GOOGLE = 'LOG_IN_GOOGLE'
export const ADD_BOOK = 'ADD_BOOK'

export const REGISTER_USER_REQUEST = '@@auth/REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = '@@auth/REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = '@@auth/REGISTER_USER_FAILURE';
